# --- Window Layout ---
# 0.0 is invisible, 1.0 is solid. 0.8 is the sweet spot for rice.
background_opacity 0.6

# This enables the frost effect (requires KDE Blur effect to be ON)

# Removes the ugly title bar for a cleaner look
hide_window_decorations no

# Window padding (makes text not hit the edges)
window_padding_width 0

# --- Performance ---
# Uses your Intel Xe GPU for buttery smooth 144Hz+ scrolling
repaint_delay 2
input_delay 1
sync_to_monitor yes
font_size 22.0
cursor #FF0000
cursor_text_color #FF0000
scrollbar_interactive yes


# BEGIN_KITTY_FONTS
font_family      family='ProFontWindows Nerd Font' postscript_name=ProFontWindowsNF
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
